#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : colcon-package-selection
Version  : 0.2.6
Release  : 14
URL      : https://files.pythonhosted.org/packages/11/3a/21e6399b11837bf11e4584ddc24675938ea5b68302cf20be758e64040013/colcon-package-selection-0.2.6.tar.gz
Source0  : https://files.pythonhosted.org/packages/11/3a/21e6399b11837bf11e4584ddc24675938ea5b68302cf20be758e64040013/colcon-package-selection-0.2.6.tar.gz
Summary  : Extension for colcon to select the packages to process.
Group    : Development/Tools
License  : Apache-2.0
Requires: colcon-package-selection-python = %{version}-%{release}
Requires: colcon-package-selection-python3 = %{version}-%{release}
Requires: colcon-core
BuildRequires : buildreq-distutils3
BuildRequires : colcon-core

%description
========================

%package python
Summary: python components for the colcon-package-selection package.
Group: Default
Requires: colcon-package-selection-python3 = %{version}-%{release}

%description python
python components for the colcon-package-selection package.


%package python3
Summary: python3 components for the colcon-package-selection package.
Group: Default
Requires: python3-core
Provides: pypi(colcon_package_selection)
Requires: pypi(colcon_core)

%description python3
python3 components for the colcon-package-selection package.


%prep
%setup -q -n colcon-package-selection-0.2.6
cd %{_builddir}/colcon-package-selection-0.2.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1588303349
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
