#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : colcon-package-selection
Version  : 0.2.5
Release  : 11
URL      : https://files.pythonhosted.org/packages/38/e5/feee426d0ac446acc1ad8d69e7b565cb377d1f993e2494236cf1f655144e/colcon-package-selection-0.2.5.tar.gz
Source0  : https://files.pythonhosted.org/packages/38/e5/feee426d0ac446acc1ad8d69e7b565cb377d1f993e2494236cf1f655144e/colcon-package-selection-0.2.5.tar.gz
Summary  : Extension for colcon to select the packages to process.
Group    : Development/Tools
License  : Apache-2.0
Requires: colcon-package-selection-python = %{version}-%{release}
Requires: colcon-package-selection-python3 = %{version}-%{release}
Requires: colcon-core
BuildRequires : buildreq-distutils3
BuildRequires : colcon-core

%description
colcon-package-selection
========================
An extension for `colcon-core <https://github.com/colcon/colcon-core>`_ to select a subset of packages for processing.

%package python
Summary: python components for the colcon-package-selection package.
Group: Default
Requires: colcon-package-selection-python3 = %{version}-%{release}

%description python
python components for the colcon-package-selection package.


%package python3
Summary: python3 components for the colcon-package-selection package.
Group: Default
Requires: python3-core

%description python3
python3 components for the colcon-package-selection package.


%prep
%setup -q -n colcon-package-selection-0.2.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1567179855
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
